basePath: /api/v1
definitions:
  cron.Cron:
    properties:
      host:
        type: string
      task_count:
        type: integer
      tasks:
        items:
          $ref: '#/definitions/cron.Task'
        type: array
      timezone:
        type: string
      user:
        type: string
    type: object
  cron.Task:
    properties:
      checksum:
        type: string
      command:
        type: string
      id:
        type: integer
      is_changed_since_lastrun:
        type: boolean
      next_run:
        type: string
      report:
        $ref: '#/definitions/report.Report'
      schedule:
        type: string
      title:
        type: string
    type: object
  report.Checksum:
    properties:
      sha256sum:
        type: string
    type: object
  report.Log:
    properties:
      content:
        type: string
      log_path:
        type: string
    type: object
  report.Report:
    properties:
      checksum:
        $ref: '#/definitions/report.Checksum'
      id:
        type: integer
      log:
        $ref: '#/definitions/report.Log'
      result:
        $ref: '#/definitions/report.Result'
      status:
        $ref: '#/definitions/report.Status'
    type: object
  report.Result:
    properties:
      result:
        type: string
      time:
        type: string
    type: object
  report.Status:
    properties:
      status:
        type: string
    type: object
host: localhost:8090
info:
  contact: {}
  description: GoAt API Document. Please notice the responses described in this document
    is response data field value, not the real response
  title: GoAt API Document
  version: "1.0"
paths:
  /api/v1/cron:
    get:
      description: List all cron tasks of the running host with execution status
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/cron.Cron'
        "500":
          description: error message
          schema:
            type: string
      summary: List all cron tasks
      tags:
      - Cron
  /api/v1/cron/{id}:
    get:
      description: Get execution status of task by specified ID
      parameters:
      - description: Task ID
        in: path
        name: id
        required: true
        type: integer
      produces:
      - application/json
      responses:
        "200":
          description: Get the task success
          schema:
            $ref: '#/definitions/report.Report'
        "400":
          description: Bad request
          schema:
            type: string
        "404":
          description: Task report not found
          schema:
            type: string
      summary: Get execution status
      tags:
      - Cron
    post:
      description: Run a task by specified ID for once
      parameters:
      - description: Task ID
        in: path
        name: id
        required: true
        type: integer
      produces:
      - application/json
      responses:
        "200":
          description: Start task success
          schema:
            type: string
        "400":
          description: Invalid Request
          schema:
            type: string
        "409":
          description: Task already running
          schema:
            type: string
      summary: Run a task by specified ID
      tags:
      - Cron
  /api/v1/ping:
    get:
      description: probing
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            type: string
      summary: Response to service probing
swagger: "2.0"
